adapter: qlora
base_model: Haleshot/Mathmate-7B-DELLA-ORPO
new_model: Haleshot/Mathmate-7B-DELLA-ORPO-everyday
bf16: true
dataset_prepared_path: null
datasets:
- path: HuggingFaceTB/everyday-conversations-llama3.1-2k
debug: null
deepspeed: null
early_stopping_patience: null
evals_per_epoch: null
flash_attention: false
fp16: false
fsdp: null
fsdp_config: null
gradient_accumulation_steps: 1
gradient_checkpointing: true
group_by_length: false
is_llama_derived_model: true
learning_rate: 0.0002
load_in_4bit: false
load_in_8bit: true
local_rank: null
logging_steps: 1
lora_alpha: 16
lora_dropout: 0.05
lora_fan_in_fan_out: null
lora_model_dir: null
lora_r: 32
lora_target_linear: true
lora_target_modules: null
lr_scheduler: cosine
max_steps: 20
micro_batch_size: 1
model_type: LlamaForCausalLM
num_epochs: 2
optimizer: paged_adamw_32bit
output_dir: ./qlora-out
pad_to_sequence_len: true
resume_from_checkpoint: null
sample_packing: true
saves_per_epoch: null
sequence_len: 1096
special_tokens: null
strict: false
tf32: false
tokenizer_type: LlamaTokenizer
train_on_inputs: false
val_set_size: 0.05
wandb_entity: null
wandb_log_model: null
wandb_name: null
wandb_project: null
wandb_watch: null
warmup_steps: 10
weight_decay: 0.0
xformers_attention: null
