wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.10
    cli_version: 0.17.9
    framework: huggingface
    huggingface_version: 4.45.0.dev0
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1727608019
    t:
      1:
      - 1
      - 9
      - 11
      - 49
      - 51
      - 55
      - 103
      - 105
      2:
      - 1
      - 9
      - 11
      - 49
      - 51
      - 55
      - 103
      - 105
      3:
      - 2
      - 23
      4: 3.10.10
      5: 0.17.9
      6: 4.45.0.dev0
      8:
      - 1
      - 5
      13: linux-x86_64
